blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import  BlogCreateView, BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_view"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("view/", BlogListView.as_view(), name="blog_view"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.AdminSite.site_header = "Управление сайтом Ломо-оптика"
admin.AdminSite.index_title = "Администрирование"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("user/", include("users.urls", namespace="users")),
    path("", include("catalog.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User


# Create your models here.
NULLABLE = dict(blank=True, null=False)


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название', help_text='Введите название')
    slug = models.CharField(max_length=150, unique=True, verbose_name='Slug', blank=True, null=True,)
    body = models.TextField(verbose_name='Содержимое', help_text='Введите содержимое')
    image_preview = models.ImageField(
        upload_to="blog/photo",
        blank=True,
        null=True,
        verbose_name="Изображение")
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_public = models.BooleanField(default=True, verbose_name='Публикация')
    count_view = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ("pk", )

blog/forms.py
from django.forms import ModelForm
from blog.models import Blog
from django import forms


class BlogForm(ModelForm):

    class Meta:
        model = Blog
        fields = ['title', 'body', 'image_preview', 'is_public', ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'image_preview': forms.FileInput(attrs={'class': 'form-control'}),
            'is_public': forms.CheckboxInput(attrs={'type': 'checkbox', 'class': 'checkbox', }),
        }


class NoneForm(ModelForm):
    """Форма для отображения пустых значений для пользователей не являющихся content-manager"""
    class Meta:
        model = Blog
        fields = []

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import BlogForm, NoneForm
from .models import Blog
from .apps import BlogConfig
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse


# Create your views here.


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_view')
    extra_context = {
        'project_name': BlogConfig.name,
        'title': 'Создать блог'
    }
    login_url = "users:login"

    def form_valid(self, form):
        # получает на вход форму, изменяет в атрибуте slug, сохраняет в БД
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)  # запоминаем slug code
            owner = self.request.user  # запоминаем владельца
            new_blog.owner = owner
            new_blog.save()
        return super().form_valid(form)


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog
    extra_context = {
        'project_name': BlogConfig.name,
        'title': 'Список блогов',
    }


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    extra_context = {
        'project_name': BlogConfig.name,
        'title': 'Детализация блога'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_view += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_view')
    extra_context = {
        'project_name': BlogConfig.name,
        'title': 'Обновление блога'
    }

    def get_form_class(self):
        try:
            self.request.user.groups.get(name='content_manager')
        except BaseException:
            return NoneForm
        else:
            return BlogForm

    def form_valid(self, form):
        # получает на вход форму, изменяет в атрибуте slug, сохраняет в БД
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin,  PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_view')

    def has_permission(self):
        return self.request.user.groups.filter(name='content_manager').exists()

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block context %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог {{ object.title }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:blog_view' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</table>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html'%}
{% block context %}
<table class="table table-striped">
    <thead>
    <tr>
        <td>
            Блог
        </td>
        <td>
        </td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            Название:
        </td>
        <td>
            {{ object.title }}
        </td>
    </tr>
    <tr>
        <td>
            Описание:
        </td>
        <td>
            {{ object.body }}
        </td>
    </tr>
    <tr>
        <td>
            Просмотры:
        </td>
        <td>
            {{object.count_view}}
        </td>
    </tr>
    </tbody>
</table>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block context %}

<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    {% if object %}
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    {% else %}
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "catalog/base.html" %} {# Расширяем содержимое базовым классом #}
{% block context %}
{% load static %}
{% load get_path_for_media %}


<section class="py-5 text-center container">
    <div class="row" align="start">
        <div class="col-2">
            <a class="btn btn-primary" href="{% url 'blog:blog_create' %}">Создать</a>
        </div>
    </div>
</section>

<div class="row">
    {% for object in object_list %}
    {% if object.is_public %}
    <div class="col-3">
        <div class="card" style="width: 18rem;">
            <img src="{{ object.image_preview|get_image_path:'/static/apology.webp' }}" class="card-img-top"
                 alt="product" width="100" height=200>
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">{{ object.body|slice:":100" }}...</p>
                <div class="container px-4 text-center">
                    <div class="row gy-0">
                        <div class="col">
                            <div class="p-1"><a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-primary">Подробнее...</a>
                            </div>
                        </div>

                        {% if perms.blog.change_blog %}
                        <div class="col">
                            <div class="p-1"><a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.blog.delete_blog %}
                        <div class="col">
                            <div class="p-1"><a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-primary">Удалить</a>
                            </div>
                        </div>
                        {% endif %}
                        <div class="alert alert-light" role="alert"> Счетчик просмотров {{ object.count_view }} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}