blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import  BlogCreateView, BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_view"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("view/", BlogListView.as_view(), name="blog_view"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.AdminSite.site_header = "Управление сайтом Ломо-оптика"
admin.AdminSite.index_title = "Администрирование"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("user/", include("users.urls", namespace="users")),
    path("", include("catalog.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from .apps import UsersConfig
from django.contrib.auth.views import LogoutView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('password-reset/', views.UserPasswordReset.as_view(), name='password_reset_form'),
    path('password-reset/done/', views.UserPasswordResetDone.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetComplete.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
NULLABLE = dict(blank=True, null=True)


class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='Email адрес')
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='Страна', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __repr__(self):
        return self.email

    def __str__(self):
        return self.email

    @property
    def is_moderator(self):
        return self.groups.filter(name='moderators').exists()

    @property
    def is_content_manager(self):
        return self.groups.filter(name='content_manager').exists()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'password', )


class RegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2', 'username', 'avatar', 'phone', 'country', )
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-input'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
            'username': forms.TextInput(attrs={'class':'form-input'}),
            'avatar': forms.FileInput(attrs={'class': 'form-input'}),
            'phone': forms.TextInput(attrs={'class': 'form-input'}),
            'country': forms.TextInput(attrs={'class': 'form-input'}),
        }

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView
from .forms import UserLoginForm, RegistrationForm
from .apps import UsersConfig
from .models import User
from django.core.mail import send_mail


# Create your views here.


class LoginUser(LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'
    extra_context = {
        'project_name': UsersConfig.name + '/login/',
        'title': 'Авторизация'
    }

    # def get_success_url(self):
    #     return reverse('catalog:product')


class RegisterView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            field = form.cleaned_data
            send_mail(
                "Congratulations! You have registered in Sky.pro sales of optical goods",
                f"""Hi, {field.get('username')}. This is a test e-mail from Sky.pro optic to Sky.
                Your email: {field.get('email')}.
                Your password: {field.get('password1')}."
                'Remember to change it after login.""",
                '21cfk8lf6gbp@mail.ru',
                [field.get('email'), 'ice_eyes@mail.ru'],
                fail_silently=False,
            )
        return super().form_valid(form)


class UserPasswordReset(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/password_reset_email.html'


class UserPasswordResetDone(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class UserPasswordResetConfirm(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class UserPasswordResetComplete(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'



# def login_user(request):
#     """makeup login"""
#     if request.method == 'POST':
#         form = UserLoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('catalog:product'))
#     else:
#         form = UserLoginForm()
#     return render(request, 'users/login.html', {'form': form})


# def logout_user(request):
#     """makeup logout"""
#     logout(request)
#     form = UserLoginForm()
#     return render(request, 'users/login.html', {'form': form})

users/templates/users/login.html
{% extends "catalog/base.html" %}

{% block context %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card-title">
                <h2>Авторизация</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <p><a href="{% url 'users:password_reset_form' %}">Забыли пароль?</a></p>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'catalog/base.html' %}

{% block context %}
<h3>Пароль изменен</h3>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
    <a href="{% url 'users:login' %}">входа в систему</a>.
</p>


{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}

{% block context %}

<h3>Новый пароль</h3>
<h4>Сгенерировать случайный пароль?</h4>
{% load static %}
{% load generate_password %}

<p>Этот пароль будет использоваться для входа в систему:</p>


<input type="text"  class="form-input" placeholder="Генерирование пароля" disabled readonly value="{% get_random_password %}">
<a href="{% url 'users:login' %}" class="btn btn-primary btn-sm active">Генерирование пароля</a>

<br>
<br>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "catalog/base.html" %}
{% load i18n %}

{% block content %}
<h3>Сброс пароля</h3>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}

{% block context %}
<h3>Восстановление пароля</h3>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p ><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

users/templates/users/register.html
{% extends "catalog/base.html" %}

{% block context %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card-title">
                <h2>Регистрация пользователя</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Зарегистрировать</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}