blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import  BlogCreateView, BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_view"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("view/", BlogListView.as_view(), name="blog_view"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),

]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import CatalogDetailView, CatalogCreateView, CatalogDeleteView, CatalogUpdateView, \
    CatalogListView

app_name = CatalogConfig.name

urlpatterns = [
    path("", CatalogListView.as_view(), name="product"),
    path(f"detail/<int:pk>/", CatalogDetailView.as_view(), name="product_detail"),
    path(f"create/", CatalogCreateView.as_view(), name="product_create"),
    path(f"edit/<int:pk>/", CatalogUpdateView.as_view(), name="product_update"),
    path(f"delete/<int:pk>/", CatalogDeleteView.as_view(), name="product_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.AdminSite.site_header = "Управление сайтом Ломо-оптика"
admin.AdminSite.index_title = "Администрирование"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("user/", include("users.urls", namespace="users")),
    path("", include("catalog.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from contacts.views import ContactView
from contacts.apps import ContactsConfig

app_name = ContactsConfig.name

urlpatterns = [
    path("", ContactView.as_view(), name="contacts"),
]

catalog/models.py
from django.db import models
from users.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(
        max_length=50, verbose_name="Название категории", help_text="Введите строку названия категории"
    )
    description = models.TextField(verbose_name="Описание категории", help_text="Введите описание категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ("id",)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название товара", help_text="Введите строку названия товара")
    description = models.TextField(verbose_name="Описание товара", help_text="Введите описание товара")
    image_preview = models.ImageField(
        upload_to="products/photo",
        blank=True,
        null=True,
        verbose_name="Фото",
        help_text="Загрузите фото товара",
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="categories",)
    price = models.FloatField(verbose_name="Стоимость товара", help_text="Введите строку стоимости товара")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)
    public = models.BooleanField(default=False, verbose_name='Признак публикации')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ("name",)
        permissions = [
            (
                "delete_public_product", "Can disable product"
            ),
            (
                "change_product_description", "Can change product description"
            ),
            (
                "change_product_category", "Can change product category"
            ),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="versions",)
    version_number = models.CharField(max_length=100, verbose_name="Номер версии")
    version_name = models.CharField(max_length=100, verbose_name='Название версии', help_text='Введите название версии')
    is_active = models.BooleanField(verbose_name='Признак текущей версии', help_text='Активно?')

    def __str__(self):
        return f"Product - {self.product}, Version - {self.version_number}"

    class Meta:
        verbose_name = "Версия продукта"
        verbose_name_plural = "Версии продуктов"
        ordering = ("product", )

contacts/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя', help_text='Введите имя')
    phone = models.CharField(max_length=10, verbose_name='Телефон', help_text='Введите телефон(не более 10 символов)')
    message = models.TextField()

    def __str__(self):
        return f"{self.name} {self.phone}"

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'
        ordering = ("name",)

catalog/forms.py
from django.forms import ModelForm
from .models import Product, Version, Category
from django import forms


class ProductForm(ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория', empty_label='Категория не выбрана')
    class Meta:
        model = Product
        fields = ['name', 'description', 'image_preview', 'category', 'price', 'public', ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image_preview': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'public': forms.CheckboxInput(attrs={'type': 'checkbox', 'class': 'checkbox', }),
        }

    def clean_name(self):
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']

        name = self.cleaned_data['name']
        print(self.cleaned_data)
        if name.lower() in forbidden_words:
            raise forms.ValidationError("Название товара не может включать запрещенные слова")
        return self.cleaned_data['name']


class ProductModeratorUpdateForm(ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория', empty_label='Категория не выбрана')
    class Meta:
        model = Product
        fields = ['name', 'description', 'image_preview', 'category', 'price', 'public', ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image_preview': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'public': forms.CheckboxInput(attrs={'type': 'checkbox', 'class': 'checkbox', }),
        }

    def clean_name(self):
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']

        name = self.cleaned_data['name']
        print(self.cleaned_data)
        if name.lower() in forbidden_words:
            raise forms.ValidationError("Название товара не может включать запрещенные слова")
        return self.cleaned_data['name']


class ProductUserUpdateForm(ModelForm):

    class Meta:
        model = Product
        fields = []


class VersionForm(ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
        widgets = {
            'version_number': forms.TextInput(attrs={'class': 'form-control'}),
            'version_name': forms.TextInput(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }
        labels = {
            'version_number': 'Номер версии',
            'version_name': 'Название версии',
            'is_active': 'Активная версия',
        }

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


from config import settings
from .models import Product, Category, Version
from .apps import CatalogConfig
from django.core.paginator import Paginator
from .forms import ProductForm, VersionForm
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from users.models import User
from .forms import ProductModeratorUpdateForm, ProductUserUpdateForm
from django.core.cache import cache

from .services import list_categories


# Create your views here.


class CatalogListView(LoginRequiredMixin, ListView):
    model = Product
    paginate_by = 8
    context_object_name = 'products'
    extra_context = {
        'project_name': CatalogConfig.name,
        'title': 'Каталог продуктов',
    }

    def get_context_data(self, *args, **kwargs):
        self.content = super().get_context_data(*args, **kwargs)
        query_list = self.get_queryset(*args, **kwargs)
        for query in query_list:
            try:
                v = Version.objects.get(pk=query.pk)
            except v.DoesNotExist:
                continue
            else:
                if v and v.is_active:
                    query.name = v.version_name + ' Version #' + v.version_number
        p = Paginator(query_list, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = p.get_page(page_number)
        self.content['page_obj'] = page_obj
        #  Список категорий из БД
        self.content['cached_categories'] = list_categories()
        return self.content


class CatalogDetailView(LoginRequiredMixin, DetailView):
    model = Product
    extra_context = {
        'project_name': CatalogConfig.name,
        'title': 'Детализация товара'
    }

    def get_object(self, queryset=None):
        """Чтение атрибутов из Кэш или БД"""
        if cache.get('cached_obj'):
            return cache.get('cached_obj')
        self.object = super().get_object(queryset)
        cache.set('cached_obj', self.object, 10)
        return cache.get('cached_obj')


class CatalogCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')
    extra_context = {
        'project_name': CatalogConfig.name,
        'title': 'Создание товара'
    }

    def form_valid(self, form):
        # получает на вход форму, сохраняет в БД
        if form.is_valid():
            user = form.save()
            user.owner = User.objects.get(username=self.request.user.username)
        return super().form_valid(form)


class CatalogUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:product')
    extra_context = {
        'project_name': CatalogConfig.name,
        'title': 'Редактирование товара'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data().get('formset')
        self.object = form.save()
        if form.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        """Переопределяет форму для модераторов и обычных пользователей"""
        try:
            self.request.user.groups.get(name='moderators')
        except BaseException:
            return ProductUserUpdateForm
        else:
            return ProductModeratorUpdateForm


class CatalogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product')
    extra_context = {
        'project_name': CatalogConfig.name,
        'title': 'Создание товара'
    }

    def has_permission(self):
        return self.request.user.groups.filter(name='moderators').exists() or \
               self.request.user.has_perm('catalog.delete_product')



# def get_product(request: WSGIRequest, product_id: int) -> HttpResponse:
#     product_values = Product.objects.get(pk=product_id)
#     obj = dict(product=product_values, project_name=CatalogConfig.name)
#     return render(request, os.path.join(CatalogConfig.name, "product.html"), context=obj)


# def send_contacts(request: WSGIRequest) -> HttpResponse:
#     """Метод POST принимает данные контактов"""
#     if request.method == "POST":
#         name = request.POST.get("name")
#         phone = request.POST.get("phone")
#         message = request.POST.get("message")
#         contact = Contact()
#         contact.name = name
#         contact.phone = phone
#         contact.message = message
#         contact.save()  # сохраняет в БД
#         resp = {'name': name, 'phone': phone, 'message': message, 'project_name': CatalogConfig.name}
#         return render(request, os.path.join(CatalogConfig.name, "contact_form.html"), resp)
#     return render(request, os.path.join(CatalogConfig.name, "contact_form.html"),
#                   {'project_name': CatalogConfig.name})

# def get_catalog(request: WSGIRequest) -> HttpResponse:
#     """Что-то нужно пояснить"""
#     product_list = Product.objects.all()
#     paginator = Paginator(product_list, 8)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     for number, product in enumerate(
#         product_list[len(product_list) - 5:], start=1
#     ):  # В контроллер отображения главной страницы добавить выборку последних пяти товаров и вывод их в консоль.
#         print(number, product)
#     obj = dict(catalog_key=product_list, project_name=CatalogConfig.name, page_obj=page_obj)
#     return render(request, os.path.join(CatalogConfig.name, "index.html"), context=obj)


# def catalog_list(request):
#     # Клон CatalogListView
#     products = Product.objects.all()
#     for product in products:
#         try:
#             v = Version.objects.get(pk=product.pk)
#         except v.DoesNotExist:
#             continue
#         else:
#             if v and v.is_active:
#                 product.name = 'Версионное название'
#     p = Paginator(products, 8)
#     page_number = request.GET.get('page')
#     page_obj = p.get_page(page_number)
#     return render(request, 'catalog/product_list.html', {'page_obj': page_obj, 'project_name': CatalogConfig.name})

contacts/views.py
from django.shortcuts import render
from django.views.generic import View
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
import os
from contacts.apps import ContactsConfig
from contacts.models import Contact

# Create your views here.


class ContactView(View):
    model = Contact
    content = {'project_name': ContactsConfig.name, 'title': 'Контакты'}
    extra_context = {}

    def get(self, request: WSGIRequest) -> HttpResponse:
        return render(request, os.path.join(ContactsConfig.name, "contact_form.html"), self.content)

    def post(self, request: WSGIRequest) -> HttpResponse:
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        contact = Contact()
        contact.name = name
        contact.phone = phone
        contact.message = message
        contact.save()  # сохраняет в БД
        resp = {'name': name, 'phone': phone, 'message': message, 'project_name': ContactsConfig.name}
        return render(request, os.path.join(ContactsConfig.name, "contact_form.html"), resp)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title> {{ title }} </title>
</head>
<body>
{% include 'catalog/includes/header.html' %}

{% block context %}
{% endblock %}


{% include 'catalog/includes/footer.html' %}

</body>
</html>

catalog/templates/catalog/contacts.html
{% extends "catalog/base.html" %} {# Расширяем содержимое базовым классом #}
{% block context %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Наименование</td>
                        <td>Ломо-оптика</td>
                    </tr>
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>Российская Федерация</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Москва, Брюсов переулок, д.4, цокольный этаж</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
        {% if name %}
        <table class="table table-striped">
            <thead>
            <tr>
                <td>
                    Введенные данные:
                </td>
                <td>
                </td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Имя:
                </td>
                <td>
                    {{ name }}
                </td>
            </tr>
            <tr>
                <td>
                    Телефон:
                </td>
                <td>
                    {{ phone }}
                </td>
            </tr>
            <tr>
                <td>
                    Сообщение:
                </td>
                <td>
                    {{message}}
                </td>
            </tr>
            </tbody>
        </table>


        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %} {# Расширяем содержимое базовым классом #}
{% block catalog %}
{% load static %}
{% load get_path_for_media %}
<div class="row justify-content-sm-center">
    <div class="col-3">
        <nav aria-label="...">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    {{page_obj.previous_page_number}}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{page_obj.number}}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    {{page_obj.next_page_number}}</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<br>
<div class="row">
    {% for product in page_obj %}
    <div class="col-3">
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image_preview|get_image_path:'/static/apology.webp' }}" class="card-img-top"
                 alt="product" width="200" height=200>
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description|slice:":100" }}...</p>
                <div class="row">
                    <div class="col-auto">
                        <a href="{{ project_name }}/{{ product.id }}" class="btn btn-primary">Подробнее...</a>
                    </div>
                    <div class="col-auto center">
                        <p class="text-dark-end m-1">{{ product.price }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block product %}
{% load static %}
<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 order-md-2">
        <p class="lead">Стоимость: {{ product.price }}</p>
        <p class="text">Наименование:</p>
        <h2 class="featurette-heading">{{ product.name }}></h2>
        <p class="text">Описание:</p>
        <p class="lead">{{ product.description }}</p>
    </div>
    <div class="col-md-5 order-md-1">
        {% if product.image_preview %}
            <img src="/media/{{ product.image_preview }}" class="card-img-top" alt="product">
        {% else %}
            <img src="{% static 'apology.webp' %}" class="card-img-top" alt="product">
        {% endif %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block context %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить {{object.name}} {{ object.title }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:product' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</table>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block context %}
{% load static %}
<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 order-md-2">
        <p class="lead">Стоимость: {{ object.price }}</p>
        <p class="text">Наименование:</p>
        <h2 class="featurette-heading">{{ object.name }}></h2>
        <p class="text">Описание:</p>
        <p class="lead">{{ object.description }}</p>
        {% if request.user.is_moderator %}
        <a class="btn btn-danger" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
        {% endif %}
        {% if request.user == object.owner or request.user.is_moderator %}
        <a class="btn btn-primary" href="{% url 'catalog:product_update' object.pk %}">  Редактировать</a>
        {% endif %}
    </div>
    <div class="col-md-5 order-md-1">
        {% if product.image_preview %}
            <img src="/media/{{ product.image_preview }}" class="card-img-top" alt="product">
        {% else %}
            <img src="{% static 'apology.webp' %}" class="card-img-top" alt="product">
        {% endif %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block context %}
<div class="col-12">
    {% if object %}
    <form action="{% url 'catalog:product_update' object.pk %}" class="row" method="post" enctype="multipart/form-data">
        {% else %}
        <form action="{% url 'catalog:product_create' %}" class="row" method="post" enctype="multipart/form-data">
            {% endif %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Редактирование продукта
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Редактирование версии
                        </h3>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for f in formset.forms %}
                        {{ f.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>
</div>


{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "catalog/base.html" %} {# Расширяем содержимое базовым классом #}
{% block context %}
{% load static %}
{% load get_path_for_media %}
<div class="row justify-content-sm-center">
    <div class="col-3">
        <nav aria-label="...">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    {{page_obj.previous_page_number}}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link"
                                                href="?page={{ page_obj.number }}">{{page_obj.number}}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    {{page_obj.next_page_number}}</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="row md-5">
    <div class="container">
        <a class="btn btn-primary" href="{% url 'catalog:product_create' %}" role="button">
            Добавить продукт
        </a>
    </div>
</div>

<div class="row-2">
    <div class="container">
        <div class="row-auto">
            <p>Список категорий: </p>
            {% for category in cached_categories %}
            <p>{{ category }}</p>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <h2>Каталог продуктов</h2>
            {% for product in page_obj %}
            <div class="col-3">
                <div class="card">
                    <img src="{{ product.image_preview|get_image_path:'/static/apology.webp' }}" class="card-img-top"
                         alt="product" width="200" height=200>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description|slice:":100" }}...</p>
                        <div class="row">
                            <div class="col-auto">
                                <a href="{% url 'catalog:product_detail' product.pk %}"
                                   class="btn btn-primary">Подробнее...</a>
                            </div>
                            <div class="col-auto center">
                                <p class="text-dark-end m-1">{{ product.price|floatformat:"2g" }} руб.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endblock %}
    </div>
</div>